# Generated by Django 3.2.18 on 2023-04-11 06:13

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_thumbnail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='thumbnail/'),
        ),
    ]
